export const environment = {
  auth: "https://localhost:7292/api/Auth",
  department: "https://localhost:7292/api/Department",
  designation: "https://localhost:7292/api/Designation",
  country: "https://localhost:7292/api/Country",
  state: "https://localhost:7292/api/State",
  city: "https://localhost:7292/api/City",
  employee: "https://localhost:7292/api/EmployeeMaster",
  employeePermission: "https://localhost:7292/api/EmployeePermission",
  task: "https://localhost:7292/api/Task",
  subTask: "https://localhost:7292/api/SubTask",
  userSubTask: "https://localhost:7292/api/SubTask",
  userTask: "https://localhost:7292/api/Task",
  dashboard: "https://localhost:7292/api/Dashboard",
  attendance: "https://localhost:7292/api/Attendance",
  leave: "https://localhost:7292/api/LeaveRequest",
}